# Getting Started with NumPy - Lab

## Introduction

Now that we have introduced NumPy, let's put it to practice. In this lab, you are going to be creating arrays, performing operations on them, and returning new arrays all using the NumPy library. Let's get started!

## Objectives

You will be able to: 

- Instantiate a numpy array with specified values 
- Use broadcasting to perform a math operation on an entire numpy array 


## Import `NumPy` under the standard alias

In [11]:
# Import numpy using the standard alias
import numpy as np

## Generate some mock data

Create a NumPy array for each of the following:
    1. Using a range
    2. Using a Python list
    
Below, create a list in Python that has 5 elements (i.e. [0,1,2,3,4]) and assign it to the variable `py_list`. 

Next, do the same, but instead of a list, create a range with 5 elements and assign it to the variable, `py_range`.

Finally, use the list and range to create NumPy arrays and assign the array from list to the variable `array_from_list`, and the array from the range to the variable `array_from_range`.

In [ ]:
# Your code here
py_list = None
py_range = None
array_from_list = None
array_from_range = None

In [3]:
py_list = [0,1,2,3,4]
py_range = range(0,5)
array_from_list = np.array(py_list)
array_from_range = np.array(py_range)
print(np.array(py_list))
print(np.array(py_range))

[0 1 2 3 4]
[0 1 2 3 4]


Next, we have a list of heights and weights and we'd like to use them to create a collection of BMIs. However, they are both in inches and pounds (imperial system), respectively. 

Let's use what we know to create NumPy arrays with the metric equivalent values (height in meters & weight in kg).

> **Remember:** *NumPy can make these calculations a lot easier and with less code than a list!*

> 1.0 inch = 0.0254 meters

> 2.2046 lbs = 1 kilogram

In [ ]:
# Use the conversion rate for turning height in inches to meters
list_height_inches = [65, 68, 73, 75, 78]

# Your code here
array_height_inches = None
array_height_meters = None

In [11]:
# Use the conversion rate for turning height in inches to meters
list_height_inches = [65, 68, 73, 75, 78]

# Your code here
array_height_inches = np.array(list_height_inches)
array_height_meters = np.multiply(array_height_inches, 0.0254) 
print(array_height_meters)

[1.651  1.7272 1.8542 1.905  1.9812]


In [ ]:
# Use the conversion rate for turning weight in pounds to kilograms
list_weight_pounds = [150, 140, 220, 205, 265]

# Your code here
array_weight_pounds = None
array_weight_kg = None

In [13]:
# Use the conversion rate for turning weight in pounds to kilograms
list_weight_pounds = [150, 140, 220, 205, 265]

# Your code here
array_weight_pounds = np.array(list_weight_pounds)
array_weight_kg = np.divide(array_weight_pounds, 2.2046)
print(array_weight_kg)

[ 68.03955366  63.50358342  99.79134537  92.98739    120.20321147]


The metric formula for calculating BMI is as follows:

> BMI = weight (kg) ÷ height^2 (m^2)

So, to get BMI we divide weight by the squared value of height. For example, if I weighed 130kg and was 1.9 meters tall, the calculation would look like:

> BMI = 130 / (1.9*1.9)

Use the BMI calculation to create a NumPy array of BMIs

In [15]:
# Your code here
BMI_array = np.divide(array_weight_kg, np.power(array_height_meters, 2))
print(BMI_array)

[24.9613063  21.28692715 29.02550097 25.62324316 30.62382485]


## Create a vector of ones the same size as your BMI vector using `np.ones()`

In [ ]:
# Your code here
identity = None
identity

In [16]:
identity = np.ones(5)
identity

array([1., 1., 1., 1., 1.])

## Multiply the BMI_array by your vector of ones
The resulting product should have the same values as your original BMI numpy array.

In [17]:
# Your code here
array_product = np.multiply(identity, BMI_array)
array_product

array([24.9613063 , 21.28692715, 29.02550097, 25.62324316, 30.62382485])

## Level Up: Using NumPy to Parse a File
The Pandas library that we've been using is built on top of NumPy; all columns/series in a Pandas DataFrame are built using NumPy arrays. To get a better idea of a how a built-in method like `pd.read_csv()` works, we'll try and recreate that here!

In [20]:
# Open a text file (csv files are just plaintext separated by commas)
f = open('bp.txt')
n_rows = len(f.readlines())
# Print number of lines in the file
print('The file has {} lines.'.format(n_rows)) 
# After using readlines, we must reopen the file
f = open('bp.txt') 
# The file has values separated by tabs; we read the first line and check it's length 
n_cols = (len(f.readline().split('\t'))) 

f = open('bp.txt')

# Your code here
# Pseudocode outline below
#1) Create a matrix of zeros that is the same size of the file
#2) Iterate through the file: "for line in f:" Hint: using enumerate will also be required
    #3) Update each row of the matrix with the new stream of data
    #Hint: skip the first row (it's just column names, not the data.)
#4) Preview your results; you should now have a NumPy matrix with the data from the file


The file has 21 lines.


In [16]:
import pandas as pd
# Open a text file (csv files are just plaintext separated by commas)
f = open('bp.txt')
n_rows = len(f.readlines())
# Print number of lines in the file
print('The file has {} lines.'.format(n_rows)) 
# After using readlines, we must reopen the file
f = open('bp.txt') 
# The file has values separated by tabs; we read the first line and check it's length 
n_cols = (len(f.readline().split('\t'))) 
print('The file has {} columns.'.format(n_cols))

print(f)

The file has 21 lines.
The file has 8 columns.
<_io.TextIOWrapper name='bp.txt' mode='r' encoding='UTF-8'>


In [34]:
# Open a text file (csv files are just plaintext separated by commas)
f = open('bp.txt')
n_rows = len(f.readlines())
# Print number of lines in the file
print('The file has {} lines.'.format(n_rows)) 
# After using readlines, we must reopen the file
f = open('bp.txt') 
# The file has values separated by tabs; we read the first line and check it's length 
n_cols = (len(f.readline().split('\t'))) 
print('The file has {} columns.'.format(n_cols))

f = open('bp.txt')
f= pd.read_csv('bp.txt', delimiter='\t')
f

The file has 21 lines.
The file has 8 columns.


Pt   BP  Age  Weight   BSA   Dur  Pulse  Stress
0    1  105   47    85.4  1.75   5.1     63      33
1    2  115   49    94.2  2.10   3.8     70      14
2    3  116   49    95.3  1.98   8.2     72      10
3    4  117   50    94.7  2.01   5.8     73      99
4    5  112   51    89.4  1.89   7.0     72      95
5    6  121   48    99.5  2.25   9.3     71      10
6    7  121   49    99.8  2.25   2.5     69      42
7    8  110   47    90.9  1.90   6.2     66       8
8    9  110   49    89.2  1.83   7.1     69      62
9   10  114   48    92.7  2.07   5.6     64      35
10  11  114   47    94.4  2.07   5.3     74      90
11  12  115   49    94.1  1.98   5.6     71      21
12  13  114   50    91.6  2.05  10.2     68      47
13  14  106   45    87.1  1.92   5.6     67      80
14  15  125   52   101.3  2.19  10.0     76      98
15  16  114   46    94.5  1.98   7.4     69      95
16  17  106   46    87.0  1.87   3.6     62      18
17  18  113   46    94.5  1.90   4.3     70      12
18  19  110   48    90.5  1.88   9.0     71      99
19  20  122   56    95.7  2.09   7.0     75      99

In [24]:
f.shape

(20, 8)

In [6]:
df= pd.read_csv('bp.txt')
df

Pt\tBP\tAge\tWeight\tBSA\tDur\tPulse\tStress
0           1\t105\t47\t85.4\t1.75\t5.1\t63\t33
1           2\t115\t49\t94.2\t2.10\t3.8\t70\t14
2           3\t116\t49\t95.3\t1.98\t8.2\t72\t10
3           4\t117\t50\t94.7\t2.01\t5.8\t73\t99
4           5\t112\t51\t89.4\t1.89\t7.0\t72\t95
5           6\t121\t48\t99.5\t2.25\t9.3\t71\t10
6           7\t121\t49\t99.8\t2.25\t2.5\t69\t42
7            8\t110\t47\t90.9\t1.90\t6.2\t66\t8
8           9\t110\t49\t89.2\t1.83\t7.1\t69\t62
9          10\t114\t48\t92.7\t2.07\t5.6\t64\t35
10         11\t114\t47\t94.4\t2.07\t5.3\t74\t90
11         12\t115\t49\t94.1\t1.98\t5.6\t71\t21
12        13\t114\t50\t91.6\t2.05\t10.2\t68\t47
13         14\t106\t45\t87.1\t1.92\t5.6\t67\t80
14       15\t125\t52\t101.3\t2.19\t10.0\t76\t98
15         16\t114\t46\t94.5\t1.98\t7.4\t69\t95
16         17\t106\t46\t87.0\t1.87\t3.6\t62\t18
17         18\t113\t46\t94.5\t1.90\t4.3\t70\t12
18         19\t110\t48\t90.5\t1.88\t9.0\t71\t99
19         20\t122\t56\t95.7\t2.09\t7.0\t75\t99

In [25]:
#Trial code
for line in enumerate(f):
    print(line)

(0, 'Pt')
(1, 'BP')
(2, 'Age')
(3, 'Weight')
(4, 'BSA')
(5, 'Dur')
(6, 'Pulse')
(7, 'Stress')


In [21]:
line(delimiter='\t')

TypeError: 'tuple' object is not callable

In [26]:
f.iloc[1]

Pt          2.0
BP        115.0
Age        49.0
Weight     94.2
BSA         2.1
Dur         3.8
Pulse      70.0
Stress     14.0
Name: 1, dtype: float64

In [27]:
f.shape

(20, 8)

In [33]:
zeros_matrix = np.zeros([20, 8])
zeros_matrix

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [29]:
zeros_matrix = f.copy()
zeros_matrix

Pt   BP  Age  Weight   BSA   Dur  Pulse  Stress
0    1  105   47    85.4  1.75   5.1     63      33
1    2  115   49    94.2  2.10   3.8     70      14
2    3  116   49    95.3  1.98   8.2     72      10
3    4  117   50    94.7  2.01   5.8     73      99
4    5  112   51    89.4  1.89   7.0     72      95
5    6  121   48    99.5  2.25   9.3     71      10
6    7  121   49    99.8  2.25   2.5     69      42
7    8  110   47    90.9  1.90   6.2     66       8
8    9  110   49    89.2  1.83   7.1     69      62
9   10  114   48    92.7  2.07   5.6     64      35
10  11  114   47    94.4  2.07   5.3     74      90
11  12  115   49    94.1  1.98   5.6     71      21
12  13  114   50    91.6  2.05  10.2     68      47
13  14  106   45    87.1  1.92   5.6     67      80
14  15  125   52   101.3  2.19  10.0     76      98
15  16  114   46    94.5  1.98   7.4     69      95
16  17  106   46    87.0  1.87   3.6     62      18
17  18  113   46    94.5  1.90   4.3     70      12
18  19  110   48    90.5  1.88   9.0     71      99
19  20  122   56    95.7  2.09   7.0     75      99

In [30]:
#Trial code
for line in enumerate(df, start =1):
    zeros_matrix[line] = df[line]
print(zeros_matrix)

KeyError: (1, 'Pt')

In [35]:
#Best code using for loop
for i, row in f.iterrows():
    zeros_matrix[i] = row.values
    
#Print the NumPy array
print(zeros_matrix)

[[  1.   105.    47.    85.4    1.75   5.1   63.    33.  ]
 [  2.   115.    49.    94.2    2.1    3.8   70.    14.  ]
 [  3.   116.    49.    95.3    1.98   8.2   72.    10.  ]
 [  4.   117.    50.    94.7    2.01   5.8   73.    99.  ]
 [  5.   112.    51.    89.4    1.89   7.    72.    95.  ]
 [  6.   121.    48.    99.5    2.25   9.3   71.    10.  ]
 [  7.   121.    49.    99.8    2.25   2.5   69.    42.  ]
 [  8.   110.    47.    90.9    1.9    6.2   66.     8.  ]
 [  9.   110.    49.    89.2    1.83   7.1   69.    62.  ]
 [ 10.   114.    48.    92.7    2.07   5.6   64.    35.  ]
 [ 11.   114.    47.    94.4    2.07   5.3   74.    90.  ]
 [ 12.   115.    49.    94.1    1.98   5.6   71.    21.  ]
 [ 13.   114.    50.    91.6    2.05  10.2   68.    47.  ]
 [ 14.   106.    45.    87.1    1.92   5.6   67.    80.  ]
 [ 15.   125.    52.   101.3    2.19  10.    76.    98.  ]
 [ 16.   114.    46.    94.5    1.98   7.4   69.    95.  ]
 [ 17.   106.    46.    87.     1.87   3.6   62.    18. 

In [16]:
#Direct conversion of Pandas dataframe to a Numpy array
ndarray = f.to_numpy()
print(ndarray)

[[  1.   105.    47.    85.4    1.75   5.1   63.    33.  ]
 [  2.   115.    49.    94.2    2.1    3.8   70.    14.  ]
 [  3.   116.    49.    95.3    1.98   8.2   72.    10.  ]
 [  4.   117.    50.    94.7    2.01   5.8   73.    99.  ]
 [  5.   112.    51.    89.4    1.89   7.    72.    95.  ]
 [  6.   121.    48.    99.5    2.25   9.3   71.    10.  ]
 [  7.   121.    49.    99.8    2.25   2.5   69.    42.  ]
 [  8.   110.    47.    90.9    1.9    6.2   66.     8.  ]
 [  9.   110.    49.    89.2    1.83   7.1   69.    62.  ]
 [ 10.   114.    48.    92.7    2.07   5.6   64.    35.  ]
 [ 11.   114.    47.    94.4    2.07   5.3   74.    90.  ]
 [ 12.   115.    49.    94.1    1.98   5.6   71.    21.  ]
 [ 13.   114.    50.    91.6    2.05  10.2   68.    47.  ]
 [ 14.   106.    45.    87.1    1.92   5.6   67.    80.  ]
 [ 15.   125.    52.   101.3    2.19  10.    76.    98.  ]
 [ 16.   114.    46.    94.5    1.98   7.4   69.    95.  ]
 [ 17.   106.    46.    87.     1.87   3.6   62.    18. 

In [7]:
ndarray.shape

(20, 8)

In [43]:
for line in df:
    #line += 1
    zeros_matrix[line] = f[line]
zeros_matrix    

TypeError: '_io.TextIOWrapper' object is not subscriptable

In [3]:
import numpy as np

In [21]:
#Ismael's code
matrix = np.zeros((n_rows-1, n_cols))

for i, line in enumerate(f):
    if i == 0:
        continue
    values = line.strip().split('\t')
    matrix[i-1] = np.array(values, dtype=float)
print(matrix)
matrix.shape

[[  1.   105.    47.    85.4    1.75   5.1   63.    33.  ]
 [  2.   115.    49.    94.2    2.1    3.8   70.    14.  ]
 [  3.   116.    49.    95.3    1.98   8.2   72.    10.  ]
 [  4.   117.    50.    94.7    2.01   5.8   73.    99.  ]
 [  5.   112.    51.    89.4    1.89   7.    72.    95.  ]
 [  6.   121.    48.    99.5    2.25   9.3   71.    10.  ]
 [  7.   121.    49.    99.8    2.25   2.5   69.    42.  ]
 [  8.   110.    47.    90.9    1.9    6.2   66.     8.  ]
 [  9.   110.    49.    89.2    1.83   7.1   69.    62.  ]
 [ 10.   114.    48.    92.7    2.07   5.6   64.    35.  ]
 [ 11.   114.    47.    94.4    2.07   5.3   74.    90.  ]
 [ 12.   115.    49.    94.1    1.98   5.6   71.    21.  ]
 [ 13.   114.    50.    91.6    2.05  10.2   68.    47.  ]
 [ 14.   106.    45.    87.1    1.92   5.6   67.    80.  ]
 [ 15.   125.    52.   101.3    2.19  10.    76.    98.  ]
 [ 16.   114.    46.    94.5    1.98   7.4   69.    95.  ]
 [ 17.   106.    46.    87.     1.87   3.6   62.    18. 

(20, 8)

## Summary

In this lab, we practiced creating NumPy arrays from both lists and ranges. We then practiced performing math operations like converting imperial measurements to metric measurements on each element of a NumPy array to create new arrays with new values. Finally, we used both of our new NumPy arrays to operate on each other and create new arrays containing the BMIs from our arrays containing heights and weights.